import * as THREE from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
const materials = new Map(), geometries = new Map();
const mergedModels=new Map();
const mat = (color, glow=false) => {const key=color+':'+glow;if(!materials.has(key)) materials.set(key,new THREE.MeshStandardMaterial({color,roughness:glow?.35:.72,metalness:glow?.4:.18,emissive:glow?color:0,emissiveIntensity:glow?.8:0}));return materials.get(key);};
const geo=(key,fn)=>{if(!geometries.has(key))geometries.set(key,fn());return geometries.get(key);};
function part(g,geometry,color,x=0,y=0,z=0,scale=[1,1,1],glow=false){const m=new THREE.Mesh(geometry,mat(color,glow));m.position.set(x,y,z);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
const sphere=(g,c,x,y,z,s=[1,1,1],glow=false)=>part(g,geo('sphere',()=>new THREE.SphereGeometry(1,10,8)),c,x,y,z,s,glow);
const box=(g,c,x,y,z,s)=>part(g,geo('box',()=>new THREE.BoxGeometry(1,1,1)),c,x,y,z,s);
const cylinder=(g,c,x,y,z,r,h,rTop=r,glow=false)=>part(g,geo(`c${r}:${h}:${rTop}`,()=>new THREE.CylinderGeometry(rTop,r,h,10)),c,x,y,z,[1,1,1],glow);
const ring=(g,c,r,y,t=.1)=>{const m=part(g,geo(`ring${r}:${t}`,()=>new THREE.TorusGeometry(r,t,5,48)),c,0,y,0,[1,1,1],true);m.rotation.x=Math.PI/2;return m;};
function rod(g,c,a,b,r=.2){const d=new THREE.Vector3(...b).sub(new THREE.Vector3(...a)),m=part(g,geo('rod',()=>new THREE.CylinderGeometry(1,1,1,6)),c,...a,[r,d.length(),r]);m.position.add(d.multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return m;}
function hero(e){const g=new THREE.Group(),body=new THREE.Group();g.add(body);g.userData.body=body;const key=e.heroId||'ahri',blue=e.team==='blue',team=blue?0x45deee:0xee5062;
const colors={ahri:0xb9234b,ashe:0x235c97,garen:0x244c8b,lux:0xe7d1a0,ezreal:0x916139},cloth=colors[key],skin=0xf4c9af,hair={ahri:0x172338,ashe:0xdcebf4,garen:0x403628,lux:0xeacf70,ezreal:0xdabc58}[key];
ring(g,team,1.6,.12,.07);
const legs=[];for(const s of [-1,1]){const l=new THREE.Group();l.position.set(s*.48,1.45,0);body.add(l);rod(l,key==='garen'?0x9da5aa:0x293140,[0,0,0],[0,-1.2,.12],.25);box(l,0x28303b,0,-1.15,.24,[.46,.35,.75]);legs.push(l);}g.userData.legs=legs;
cylinder(body,cloth,0,2.0,0,.9,1.55,.65);sphere(body,skin,0,3.42,0,[.58,.69,.56]);sphere(body,hair,0,3.78,-.1,[.64,.45,.6]);box(body,0xcab784,0,1.55,.78,[1.4,.18,.12]);
for(const s of [-1,1]){sphere(body,key==='garen'?0xbac5c8:cloth,s*.93,2.66,0,[key==='garen'?.65:.34,.39,.38]);rod(body,cloth,[s*.93,2.55,0],[s*1.15,1.93,.4],.22);sphere(body,skin,s*1.15,1.9,.4,[.22,.25,.22]);}
if(key==='ahri'){for(const s of [-1,1]){const ear=part(body,geo('ear',()=>new THREE.ConeGeometry(.28,.9,4)),hair,s*.42,4.25,0);ear.rotation.z=-s*.22;}
const tails=[];for(let i=0;i<9;i++){const t=new THREE.Group();t.position.set(0,1.85,-.45);body.add(t);const angle=(i-4)*.27;rod(t,0xe7dddf,[0,0,0],[Math.sin(angle)*2.3,1.1,-Math.cos(angle)*2.1],.42);sphere(t,0xfaf2ee,Math.sin(angle)*2.9,1.2,-Math.cos(angle)*2.65,[.45,.55,.9]);t.rotation.x=(i%3)*.18;tails.push(t);}g.userData.tails=tails;sphere(body,0x41e6ec,1.2,2.1,1.05,[.53,.53,.53],true);}
if(key==='ashe'){const cloak=part(body,geo('cloak',()=>new THREE.ConeGeometry(1.35,2.4,8,1,true)),0x193d70,0,1.85,-.5,[1,1,.65]);cloak.rotation.x=.1;const bow=part(body,geo('bow',()=>new THREE.TorusGeometry(1.2,.12,5,18,Math.PI)),0x62dff9,-1.3,2.4,.6,[1,1,1],true);bow.rotation.z=-Math.PI/2;rod(body,0xc2f5ff,[-1.3,1.2,.6],[-1.3,3.6,.6],.04);}
if(key==='garen'){box(body,0xc1c8c9,0,2.4,.66,[1.15,1.05,.17]);box(body,0xd2b66a,0,2.38,.78,[.14,.8,.16]);box(body,0x284b91,0,2.1,-.69,[1.5,1.9,.14]);const sword=new THREE.Group();sword.position.set(1.25,1.92,.45);body.add(sword);box(sword,0xd5e2e5,0,1.05,.1,[.32,2.9,.14]);box(sword,0xd2b15f,0,-.12,.1,[1,.15,.25]);box(sword,0x644b37,0,-.45,.1,[.18,.5,.18]);sword.rotation.z=-.24;g.userData.sword=sword;const spin=part(g,geo('spinRing',()=>new THREE.RingGeometry(3.8,4.25,48)),0xe7c875,0,.3,0,[1,1,1],true);spin.rotation.x=-Math.PI/2;spin.visible=false;g.userData.spinRing=spin;}
if(key==='lux'){cylinder(body,0xf0e6cf,0,1.5,0,1.12,1.3,.72);rod(body,0xd7bb65,[1.18,.65,.4],[1.18,4.25,.4],.1);ring(body,0xf9df8e,.45,4.18,.11).position.x=1.18;sphere(body,0xffee9a,1.18,4.2,.4,[.27,.35,.27],true);sphere(body,hair,-.45,3.25,-.27,[.22,.8,.35]);sphere(body,hair,.45,3.25,-.27,[.22,.8,.35]);}
if(key==='ezreal'){box(body,0x405267,0,2.53,.73,[1.2,.38,.12]);box(body,0xbba374,-1.1,2,.45,[.65,.54,.62]);sphere(body,0x4ecaf3,-1.12,2,.85,[.28,.28,.2],true);box(body,0x493c2c,0,2.25,-.6,[1.1,1.05,.35]);box(body,0x987d4e,0,3.87,.5,[1.02,.23,.2]);}
const shield=new THREE.Mesh(geo('shield',()=>new THREE.SphereGeometry(1,16,12)),new THREE.MeshBasicMaterial({color:team,transparent:true,opacity:.14,depthWrite:false}));shield.position.y=2.4;shield.scale.set(2.05,2.55,2.05);shield.visible=false;shield.renderOrder=3;g.add(shield);g.userData.shield=shield;
return g;}
function structure(e){const g=new THREE.Group(),color=e.team==='blue'?0x36d3e8:0xef3c61;
if(e.kind==='nexus'){cylinder(g,0x27323b,0,.6,0,7.2,1.2);cylinder(g,0x56616a,0,1.35,0,5.8,.6);ring(g,color,5.1,1.75,.2);const crystal=part(g,geo('crystal',()=>new THREE.OctahedronGeometry(1)),color,0,5.2,0,[3,4.5,3],true);g.userData.crystal=crystal;for(let i=0;i<6;i++){const a=i*Math.PI/3;const p=new THREE.Group();p.position.set(Math.cos(a)*5.9,0,Math.sin(a)*5.9);g.add(p);cylinder(p,0x566570,0,2.2,0,.6,3.4,.4);sphere(p,color,0,4,0,[.35,.35,.35],true);}}
else if(e.kind==='inhibitor'){cylinder(g,0x3a4a55,0,.5,0,3.5,1);ring(g,color,2.7,1,.15);part(g,geo('crystal',()=>new THREE.OctahedronGeometry(1)),color,0,2.4,0,[1.7,2.2,1.7],true);}
else {cylinder(g,0x3c4850,0,.5,0,3.35,1);cylinder(g,0x60656a,0,1.2,0,2.5,.6);cylinder(g,0x53626a,0,3.4,0,1.7,4.0,1.35);cylinder(g,0x919084,0,5.5,0,2.1,.5);cylinder(g,0x455663,0,6.4,0,1.3,1.5,.9);part(g,geo('crystal',()=>new THREE.OctahedronGeometry(1)),color,0,8.3,0,[1.1,1.8,1.1],true);for(let i=0;i<4;i++){const a=i*Math.PI/2;box(g,0x8a8c85,Math.cos(a)*1.9,5.8,Math.sin(a)*1.9,[.8,1.3,.8]);}ring(g,color,2.65,1.55,.12);}
return g;}
function minion(e){const g=new THREE.Group(),c=e.team==='blue'?0x3384c3:0xb1394a,type=e.minionType||e.type||'melee',caster=['caster','ranged'].includes(type);
if(type==='cannon'){box(g,0x493f35,0,.8,0,[2.15,.7,2.7]);box(g,c,0,1.4,-.45,[1.7,.6,1.7]);const barrel=cylinder(g,0x566570,0,1.85,.6,.36,2.45,.48);barrel.rotation.x=Math.PI/2;const muzzle=cylinder(g,0x202d34,0,1.85,1.9,.34,.13);muzzle.rotation.x=Math.PI/2;const wheels=[];for(const side of [-1,1])for(const zz of [-.85,.85]){const wheel=part(g,geo('wheel',()=>new THREE.CylinderGeometry(.66,.66,.27,10).rotateZ(Math.PI/2)),0x6f6250,side*1.15,.67,zz);sphere(g,0xbba575,side*1.32,.67,zz,[.15,.2,.2]);wheels.push(wheel);}g.userData.wheels=wheels;part(g,geo('hood',()=>new THREE.ConeGeometry(.58,.9,8)),c,0,2.2,-.7);return g;}
cylinder(g,0x252e38,0,.65,0,.65,.8);cylinder(g,c,0,1.4,0,.8,1,.5);sphere(g,0xd6b494,0,2.1,0,[.38,.43,.38]);part(g,geo('hood',()=>new THREE.ConeGeometry(.58,.9,8)),c,0,2.55,0);if(caster){rod(g,0x6e5536,[.8,.7,.2],[.8,2.7,.2],.1);sphere(g,e.team==='blue'?0x58ddff:0xff6d86,.8,2.75,.2,[.25,.3,.25],true);}else{box(g,0x848d8a,-.82,1.5,.4,[.18,1.1,.95]);rod(g,0xb5c6cb,[.75,1.4,.5],[.75,2.8,.6],.1);}if(type==='super'){g.scale.setScalar(1.48);box(g,0x8997a3,0,1.65,.55,[1.1,.95,.22]);for(const side of [-1,1])sphere(g,0xb9b8ab,side*.8,1.8,0,[.5,.42,.5]);}return g;}
function monster(e){const g=new THREE.Group(),type=e.monsterType||e.type||e.name||'',dragon=/dragon|龙/i.test(type),baron=/baron|纳什/i.test(type),large=dragon||baron;
if(type==='wolves'){sphere(g,0x586773,0,1.5,0,[1.1,.95,2]);sphere(g,0x87929a,0,2.05,1.8,[.68,.72,.78]);sphere(g,0x657680,0,1.85,2.45,[.46,.35,.6]);sphere(g,0x18252d,0,1.9,2.92,[.25,.17,.17]);for(const side of [-1,1]){part(g,geo('wolfEar',()=>new THREE.ConeGeometry(.3,.85,4)),0x6e7d84,side*.45,2.85,1.65);sphere(g,0x77d6d5,side*.49,2.19,2.28,[.12,.12,.1],true);for(const zz of [-1.1,1])rod(g,0x4c5b68,[side*.7,1.3,zz],[side*.85,.3,zz+.2],.25);}rod(g,0x7f8c92,[0,1.4,-1.4],[0,1.6,-3],.3);return g;}
if(type==='raptors'){sphere(g,0x77526c,0,1.5,0,[1.35,1.4,1.4]);sphere(g,0x9c485a,0,2.7,1,[.65,.67,.75]);const beak=part(g,geo('beak',()=>new THREE.ConeGeometry(.4,1.3,4)),0xb09569,0,2.6,1.8);beak.rotation.x=Math.PI/2;for(const side of [-1,1]){sphere(g,0xf1c664,side*.5,2.85,1.25,[.12,.13,.12],true);rod(g,0x9d8267,[side*.7,1,0],[side*.8,.15,.4],.17);sphere(g,0x5e4965,side*1.2,1.5,-.2,[.5,1.0,1.5]);}for(let i=0;i<3;i++)rod(g,0x9b5366,[(i-1)*.4,1.7,-.8],[(i-1)*.8,2.5,-2],.17);return g;}
const c=baron?0x6d407c:dragon?0x665641:type==='blue'?0x697c82:type==='red'?0x75534a:0x516f69; sphere(g,c,0,large?3.6:1.7,0,large?[3.2,2.7,4]:[1.8,1.6,1.8]);sphere(g,c,0,large?5:2.6,large?3.8:1.7,large?[1.5,1.3,2]:[.8,.7,1]);for(const s of [-1,1]){sphere(g,baron?0xff9cd8:0xf6cf66,s*.75,large?5.4:2.8,large?5.2:2.45,[.17,.18,.17],true);for(let i=0;i<2;i++)rod(g,c,[s*(large?2.5:1.3),large?3:1.3,i*(large?4:1.8)-(large?2:1)], [s*(large?3.8:1.7),.6,i*(large?4:1.8)-(large?2:1)],large?.7:.4);}
if(type==='blue'||type==='red'){const glow=type==='blue'?0x4ed4ed:0xee6553;part(g,geo('crystal',()=>new THREE.OctahedronGeometry(1)),glow,0,1.8,1.6,[.8,1.1,.6],true);for(const side of [-1,1]){part(g,geo('crystal',()=>new THREE.OctahedronGeometry(1)),glow,side*1.6,2.5,0,[.55,1.0,.6],true);sphere(g,c,side*1.9,1.3,.8,[.65,.9,.65]);}}
if(dragon){g.userData.wings=[];if(!materials.has('dragon-wing'))materials.set('dragon-wing',new THREE.MeshStandardMaterial({color:0x826144,side:THREE.DoubleSide,roughness:.8}));for(const s of [-1,1]){const shape=new THREE.Shape();shape.moveTo(0,0);shape.lineTo(s*9,5);shape.lineTo(s*7,-3);shape.lineTo(s*3,-1);shape.closePath();const w=new THREE.Mesh(geo(`dragonWing${s}`,()=>new THREE.ShapeGeometry(shape)),materials.get('dragon-wing'));w.position.set(s*2,4,-1);w.rotation.x=-.5;w.castShadow=true;g.add(w);g.userData.wings.push(w);rod(g,0xb6a07d,[s*2,4,-1],[s*9,6.5,-3.5],.15);}rod(g,c,[0,3,-3],[0,2,-8],1);}
if(baron){for(let i=0;i<5;i++)rod(g,0x896492,[Math.sin(i)*2,5,0],[Math.sin(i)*3,8+i*.6,-1],.5);part(g,geo('horn',()=>new THREE.ConeGeometry(.6,2,6)),0xc3a1cb,0,7,4);}
return g;}
export function createActor(e){const g=e.kind==='hero'?hero(e):['tower','nexus','inhibitor'].includes(e.kind)?structure(e):e.kind==='monster'?monster(e):e.kind==='ward'?ward(e):minion(e);g.position.set(e.x,0,e.z);g.userData.entityId=e.id;return g;}
function ward(e){const g=new THREE.Group();cylinder(g,0x857247,0,1,0,.3,1.8);const eye=sphere(g,0x75ffc8,0,2.1,0,[.68,.45,.35],true);sphere(g,0x152d2b,0,2.15,.32,[.2,.28,.1]);ring(g,0x50c79d,.85,.18,.07);return g;}
function mergeStaticModel(group,e,directOnly=false){
 const key=[e.kind,e.team,e.heroId,e.minionType,e.monsterType,directOnly].join(':'),dynamic=new Set([group.userData.crystal,...(group.userData.wheels||[]),...(group.userData.wings||[])]),parts=[];
 if(directOnly)parts.push(...group.children.filter(o=>o.isMesh&&!dynamic.has(o)));else group.traverse(o=>{if(o.isMesh&&!dynamic.has(o))parts.push(o);});
 let model=mergedModels.get(key);
 if(!model){group.updateMatrixWorld(true);const inverse=group.matrixWorld.clone().invert(),buckets=new Map();for(const object of parts){let geometry=object.geometry.index?object.geometry.toNonIndexed():object.geometry.clone();geometry.deleteAttribute('uv');geometry.applyMatrix4(new THREE.Matrix4().multiplyMatrices(inverse,object.matrixWorld));if(!buckets.has(object.material))buckets.set(object.material,[]);buckets.get(object.material).push(geometry);}model=[];for(const [material,list] of buckets){const geometry=mergeGeometries(list,false);list.forEach(g=>g.dispose());if(geometry)model.push({geometry,material});}mergedModels.set(key,model);}
 for(const object of parts)object.parent?.remove(object);
 for(const entry of model){const object=new THREE.Mesh(entry.geometry,entry.material);object.castShadow=true;object.receiveShadow=true;group.add(object);}
}
function missile(p){
 const group=new THREE.Group(),hero=p.hero,ultimate=p.skill==='R',color=hero==='ahri'?(p.skill==='E'?0xf68cbf:0x5ee8f4):hero==='ashe'?0x9de9ff:hero==='lux'?0xffe9a6:hero==='ezreal'?0x68d7f4:p.team==='blue'?0x5bcee7:0xff7a8d;
 const size=ultimate?.9:p.skill==='attack'?.24:.5;
 if(hero==='ashe'){const head=part(group,geo('arrowhead',()=>new THREE.ConeGeometry(1,2.5,4)),color,0,0,.5,[size,size,size],true);head.rotation.x=Math.PI/2;rod(group,color,[0,0,-1.2],[0,0,.4],ultimate?.15:.045);}
 else{sphere(group,color,0,0,0,[size,size,size],true);const streak=part(group,geo('missileTrail',()=>new THREE.ConeGeometry(1,1,6)),color,0,0,-1.1,[size*.6,2.2,size*.6],true);streak.rotation.x=-Math.PI/2;if(hero==='ezreal'&&ultimate){const arc=part(group,geo('ezArc',()=>new THREE.TorusGeometry(2,.16,4,14,Math.PI)),0xf1d99b,0,0,.1,[1,1,1],true);arc.rotation.z=-Math.PI/2;}}
 return group;
}
export class Actors {
 constructor(scene,labels){this.scene=scene;this.labels=labels;this.map=new Map();this.fx=[];this.projectiles=new Map();this.zones=new Map();this._projection=new THREE.Vector3();}
 clear(){for(const {mesh,label} of this.map.values()){this.scene.remove(mesh);mesh.userData.shield?.material.dispose();label?.remove();}this.map.clear();for(const mesh of this.projectiles.values())this.scene.remove(mesh);this.projectiles.clear();for(const mesh of this.zones.values()){this.scene.remove(mesh);mesh.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});}this.zones.clear();this.fx.forEach(f=>this.removeFx(f));this.fx=[];}
 sync(game,dt,time,camera,width,height,active=true){this.game=game;const keep=new Set();for(const e of game.entities){if(!e.alive&&e.kind!=='hero')continue;keep.add(e.id);let a=this.map.get(e.id);if(!a){const mesh=createActor(e);if(e.kind!=='hero'){mesh.position.set(0,0,0);mergeStaticModel(mesh,e);mesh.position.set(e.x,0,e.z);}else mergeStaticModel(mesh.userData.body,e,true);this.scene.add(mesh);let label;if(e.kind!=='ward'){label=document.createElement('div');label.className=`entity-label ${e.kind} ${e.team} ${e.id===game.player.id?'player':''}`;label.innerHTML=`<span class="entity-name"></span><div class="entity-health"><i></i></div>`;this.labels.append(label);}a={mesh,label,lastX:e.x,lastZ:e.z};this.map.set(e.id,a);}
 const visible=e.alive&&(e.team==='blue'||!active||!game.isVisible||game.isVisible(e));a.mesh.visible=visible;if(a.label)a.label.style.display=visible?'':'none';if(!visible)continue;
 const dx=e.x-a.lastX,dz=e.z-a.lastZ;const moving=Math.hypot(dx,dz)>.006;if(['hero','minion','monster'].includes(e.kind)){const angle=a.aimUntil>game.time?a.aimAngle:moving?Math.atan2(dx,dz):Number.isFinite(e.facing)?Math.PI/2-e.facing:null;if(angle!==null){const diff=THREE.MathUtils.euclideanModulo(angle-a.mesh.rotation.y+Math.PI,Math.PI*2)-Math.PI;a.mesh.rotation.y+=diff*(1-Math.exp(-dt*15));}}
 a.mesh.position.set(e.x,0,e.z);if(a.mesh.userData.body){a.mesh.userData.body.position.y=moving?Math.sin(time*13)*.12:Math.sin(time*2)*.05;const ls=a.mesh.userData.legs||[];ls.forEach((l,i)=>l.rotation.x=moving?Math.sin(time*12+i*Math.PI)*.5:0);(a.mesh.userData.tails||[]).forEach((t,i)=>t.rotation.z=Math.sin(time*2+i*.55)*.11);const spinning=e.spinUntil>game.time||e.spinning;if(spinning)a.mesh.userData.body.rotation.y+=dt*15;else a.mesh.userData.body.rotation.y=0;if(a.mesh.userData.spinRing){a.mesh.userData.spinRing.visible=!!spinning;a.mesh.userData.sword.rotation.z=spinning?-Math.PI/2:-.24;}if(a.mesh.userData.shield){a.mesh.userData.shield.visible=e.shield>0&&e.shieldUntil>game.time;a.mesh.userData.shield.material.opacity=.12+Math.sin(time*4)*.025;}}
 for(const wheel of a.mesh.userData.wheels||[])if(moving)wheel.rotation.x+=Math.hypot(dx,dz)*1.5;
 for(const wing of a.mesh.userData.wings||[])wing.rotation.x=-.5+Math.sin(time*1.7)*.055;
 if(a.mesh.userData.crystal){a.mesh.userData.crystal.rotation.y=time*.3;a.mesh.userData.crystal.position.y=5.2+Math.sin(time*2)*.2;}
 if(a.label){const h=e.kind==='hero'?6.0:e.kind==='tower'?11:e.kind==='nexus'?12:e.kind==='inhibitor'?5:e.kind==='monster'?(['dragon','baron'].includes(e.monsterType)?10:4.6):e.minionType==='super'?5:3.8;this._projection.set(e.x,h,e.z).project(camera);const on=this._projection.z<1&&this._projection.x>-1.1&&this._projection.x<1.1&&this._projection.y>-1.1&&this._projection.y<1.1;a.label.style.display=on?'':'none';a.label.style.transform=`translate(${(this._projection.x*.5+.5)*width}px,${(-this._projection.y*.5+.5)*height}px) translate(-50%,-100%)`;a.label.querySelector('i').style.width=`${Math.max(0,e.hp/e.maxHp)*100}%`;a.label.querySelector('.entity-name').textContent=e.kind==='hero'?`${e.id===game.player.id?'你 · ':''}${e.name||e.heroId} ${e.level||1}`:e.kind==='monster'?(e.name||'野怪'):'';}
 a.lastX=e.x;a.lastZ=e.z;
 }
 for(const [id,a] of this.map)if(!keep.has(id)){this.scene.remove(a.mesh);a.label?.remove();this.map.delete(id);}
 const projectiles=new Set();for(const p of game.projectiles||[]){if(p.dead)continue;projectiles.add(p.id);let mesh=this.projectiles.get(p.id);if(!mesh){mesh=missile(p);this.scene.add(mesh);this.projectiles.set(p.id,mesh);}mesh.position.set(p.x,2.4,p.z);mesh.rotation.y=Math.atan2(p.dx,p.dz);mesh.visible=!active||p.team==='blue'||!game.isVisible||game.isVisible({alive:true,kind:'projectile',team:p.team,x:p.x,z:p.z,lastDamagedAt:game.time});}
 for(const [id,mesh] of this.projectiles)if(!projectiles.has(id)){this.scene.remove(mesh);this.projectiles.delete(id);}
 const zones=new Set();for(const zone of game.zones||[]){if(zone.dead)continue;const id=zone.sourceId;zones.add(id);let group=this.zones.get(id);if(!group){group=new THREE.Group();const material=new THREE.MeshBasicMaterial({color:0xf1dfaa,transparent:true,opacity:.32,side:THREE.DoubleSide,depthWrite:false});const edge=new THREE.Mesh(new THREE.RingGeometry(zone.radius*.94,zone.radius,64),material);edge.rotation.x=-Math.PI/2;group.add(edge);const fill=new THREE.Mesh(new THREE.CircleGeometry(zone.radius,48),material.clone());fill.material.opacity=.06;fill.rotation.x=-Math.PI/2;group.add(fill);this.scene.add(group);this.zones.set(id,group);}group.position.set(zone.x,.21,zone.z);group.children[0].material.opacity=.26+Math.sin(time*3)*.07;group.visible=!active||zone.team==='blue'||!game.isVisible||game.isVisible({alive:true,kind:'zone',team:zone.team,x:zone.x,z:zone.z,lastDamagedAt:game.time});}
 for(const [id,group] of this.zones)if(!zones.has(id)){this.scene.remove(group);group.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});this.zones.delete(id);}
 for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.age+=dt;if(f.age>=f.duration){this.removeFx(f);this.fx.splice(i,1);continue;}const t=f.age/f.duration;if(f.mode==='bolt'){f.mesh.position.lerpVectors(f.from,f.to,t);f.mesh.scale.setScalar(.8+Math.sin(t*Math.PI)*.3);}else if(f.mode==='beam'){f.mesh.material.opacity=(1-t)*.8;}else if(f.mode==='float'){f.el.style.opacity=1-t;this._projection.set(f.x,5+f.age*5,f.z).project(camera);f.el.style.transform=`translate(${(this._projection.x*.5+.5)*width}px,${(-this._projection.y*.5+.5)*height}px)`;}else{f.mesh.scale.setScalar(1+t*3);f.mesh.material.opacity=1-t;}}
 }
 removeFx(f){if(f.mesh){this.scene.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose();}f.el?.remove();}
 pulse(x,z,color=0x55e9c1,radius=1.4,duration=.7){const mesh=new THREE.Mesh(new THREE.RingGeometry(radius*.85,radius,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:1,side:THREE.DoubleSide,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.set(x,.2,z);this.scene.add(mesh);this.fx.push({mesh,age:0,duration,mode:'ring'});}
 bolt(from,to,color=0x68e8ff,size=.35,duration=.3){const mesh=new THREE.Mesh(new THREE.SphereGeometry(size,8,6),new THREE.MeshBasicMaterial({color}));mesh.position.copy(from);this.scene.add(mesh);this.fx.push({mesh,age:0,duration,mode:'bolt',from,to});}
 beam(from,to,color=0x72efff,r=.3,duration=.45){const d=to.clone().sub(from),mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d.length(),8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,depthWrite:false}));mesh.position.copy(from).add(d.clone().multiplyScalar(.5));mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());this.scene.add(mesh);this.fx.push({mesh,age:0,duration,mode:'beam'});}
 floating(x,z,text,color='#fff'){const el=document.createElement('div');el.className='floating-text';el.style.color=color;el.textContent=text;this.labels.append(el);this.fx.push({el,age:0,duration:1.2,mode:'float',x,z});}
 event(e){const c=e.color||(e.team==='red'?0xff6078:0x74e9ff);const x=e.x??e.toX??0,z=e.z??e.toZ??0,source=this.game?.getEntity?.(e.source),liveMissiles=Array.isArray(this.game?.projectiles);if(e.type==='damage')this.floating(x,z,Math.round(e.amount||0),e.team==='blue'?'#ffe9b9':'#ff8b8b');if(e.type==='gold')this.floating(x,z,`+${e.amount||0} 金币`,'#e8c775');if(['attack','spell'].includes(e.type)){const actor=this.map.get(e.source),dx=(e.toX??x)-(e.fromX??x),dz=(e.toZ??z)-(e.fromZ??z);if(actor&&Math.hypot(dx,dz)>.1){actor.aimAngle=Math.atan2(dx,dz);actor.aimUntil=(this.game?.time||0)+.5;}}if(e.type==='attack'){if(!liveMissiles)this.bolt(new THREE.Vector3(e.fromX??x,2.4,e.fromZ??z),new THREE.Vector3(e.toX??x,2.4,e.toZ??z),c,.23,.22);else if(source?.attackRange<=8)this.pulse(x,z,c,.45,.18);}
 if(e.type==='spell'){const from=new THREE.Vector3(e.fromX??x,2.5,e.fromZ??z),to=new THREE.Vector3(e.toX??x,2.5,e.toZ??z),hero=e.hero||e.heroId,hasMissile=liveMissiles&&({ahri:['Q','E'],ashe:['W','R'],lux:['Q'],ezreal:['Q','W','R']}[hero]||[]).includes(e.key);if(e.key==='D'){this.pulse(from.x,from.z,0xffdf83,2);this.pulse(to.x,to.z,0xffdf83,2);}else if(hero==='lux'&&e.key==='R'){this.beam(from,to,0xffdf8c,1,.8);this.beam(from,to,0xfffae2,.22,.85);}else if(hero==='garen'&&e.key==='R'){this.beam(new THREE.Vector3(x,22,z),new THREE.Vector3(x,.4,z),0xffe299,.75,.7);this.pulse(x,z,0xffd270,3,.7);}else if(e.key==='SPIN'){}else if(hasMissile)this.pulse(from.x,from.z,c,.8,.2);else if(hero==='lux'&&e.key==='E'){}else if(hero==='lux'&&e.key==='W')this.beam(from,to,0xffe9ac,.16,.35);else if(['MARK','ICE','E2'].includes(e.key))this.pulse(x,z,c,Math.min(5,e.radius||3),.6);else if((hero==='garen'||hero==='ashe'&&e.key==='Q'||hero==='ahri'&&e.key==='W'))this.pulse(from.x,from.z,c,2,.5);else if(from.distanceTo(to)>.2){this.bolt(from,to,c,e.key==='R'?.8:.55,.45);this.beam(from,to,c,.08,.22);}else this.pulse(x,z,c,Math.min(4,e.radius||2),.6);}
 if(['ward','death','level','recall'].includes(e.type))this.pulse(x,z,e.type==='death'?0xff5f65:e.type==='level'?0xf7d789:0x53e7d1,e.type==='death'?2.5:2,1);}
}
