import {CHAMPIONS} from './champions.js';
import {SKINS,getSkin} from './cosmetics-data.js';
import {heroPrice,ownsHero,buyHero,buySkin,equipSkin,equippedSkin,claimDaily} from './profile.js';
import {HeroPreview} from './hero-preview.js';
import './collection.css';

const $=id=>document.getElementById(id);
const cssColor=value=>typeof value==='number'?`#${value.toString(16).padStart(6,'0')}`:value;
const playstyles={twistedfate:'在蓝、红、黄牌之间精准选牌，用三张万能牌清线消耗。命运显露敌方英雄，再开启传送支援边路。',kaisa:'普攻与虚空索敌叠加电浆，在第五层爆发。购买攻击力、法强与攻速装备进化技能，再用猎手本能切入战场。',camille:'用精准礼仪的第二刀打出真实伤害，战术横扫外沿回血。钩索借地形切入，再用最后通牒锁定对手。',annie:'积攒嗜火，用火熊与扇形烈焰制造爆发。带眩晕的提伯斯能成为团战的开场。',brand:'先点燃，再控制。火焰在敌群之间连锁弹跳，三层炽焰引发范围爆炸。',morgana:'用暗之禁锢留住敌人，让暗影池持续侵蚀。黑暗之盾保护自己与队友免受控制。',veigar:'用 Q 补刀永久积攒法强，以环形牢笼限制走位，再用陨石与大招完成击杀。',ziggs:'弹跳炸弹远程消耗，地雷封路，炸药包击退。超大炸弹能支援远处的团战。',fizz:'穿梭敌阵的近战刺客。巨鲨创造击杀机会，古灵精怪帮助躲开危险。',masteryi:'无极剑道让普攻附带真实伤害，高原血统加速收割。冥想回复生命，阿尔法突袭穿梭敌群。',leesin:'音波命中后再突进，借队友位移与护盾调整位置。一脚猛龙摆尾改变团战阵型。',darius:'外圈斧刃回血，铁手拉回敌人。叠满出血后，用断头台处决并重置大招。',malphite:'厚重护盾与岩石之躯抵挡进攻。势不可挡冲入敌阵，将落点敌人一起击飞。',blitzcrank:'机械飞爪抓回敌人，接铁拳击飞与电场沉默。一记好钩就能改变整个战局。',leona:'用光剑贴近敌人，盾击接日炎耀斑连续控制。护盾与减伤帮助你站在队伍最前方。',vayne:'翻滚寻找输出位置，连续攻击触发三环真实伤害。恶魔审判把敌人钉在地形边缘。',caitlyn:'超远普攻、夹子与绳网控制距离。把敌人逼入陷阱，以爆头和狙击收尾。',missfortune:'切换攻击目标获取额外伤害，弹射子弹消耗兵线。先用弹雨减速，再以弹幕覆盖战场。',sona:'音符进攻、治疗护盾与加速光环交替保护队友。用狂舞终乐章控制一整排敌人。'};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export class CollectionView{
 constructor({profile,base,styles,onHero,onSave,notify}){
  Object.assign(this,{profile,base,styles,onHero,onSave,notify});this.role='all';this.heroId=CHAMPIONS[0].id;this.skinId='default';this.preview=new HeroPreview($('hero-preview'));
  $('hero-search').addEventListener('input',()=>this.renderRoster());
  $('hero-filters').addEventListener('click',e=>{const b=e.target.closest('[data-role]');if(!b)return;this.role=b.dataset.role;this.renderRoster();});
  $('hero-grid').addEventListener('click',e=>{const b=e.target.closest('[data-hero]');if(b)this.select(b.dataset.hero);});
  $('skin-options').addEventListener('click',e=>{const b=e.target.closest('[data-skin]');if(!b)return;this.skinId=b.dataset.skin;this.renderSkins();this.preview.setHero(this.heroId,this.skinId);});
  $('hero-skills-preview').addEventListener('click',e=>{const b=e.target.closest('[data-preview-skill]');if(b)this.showSkill(b.dataset.previewSkill);});
  $('unlock-hero').addEventListener('click',()=>{const result=buyHero(profile,this.heroId,CHAMPIONS);if(!result.ok)return notify(result.reason);onSave();this.select(this.heroId);notify(`已解锁 ${CHAMPIONS.find(h=>h.id===this.heroId).name}`);});
  $('skin-action').addEventListener('click',()=>{if(this.skinId==='default'||profile.skins.includes(this.skinId)){if(equipSkin(profile,this.heroId,this.skinId,SKINS)){onSave();this.renderSkins();notify('外观已装备，下次进入峡谷生效');}}else{const result=buySkin(profile,this.skinId,SKINS);if(!result.ok)return notify(result.reason);onSave();this.renderWallet();this.renderSkins();notify(`已解锁并装备 ${getSkin(this.skinId).name}`);}});
  $('daily-supply').addEventListener('click',()=>{const result=claimDaily(profile,today());if(result.ok){onSave();this.renderWallet();this.renderDetail();notify('每日补给到账：+1,200 蓝色精粹');}});
  $('practice-toggle').addEventListener('change',()=>this.updateStart());
  $('roster-count').textContent=`${CHAMPIONS.length} 位英雄`;
 }
 style(hero){return this.styles[hero.id]||{heading:hero.title,description:playstyles[hero.id]||hero.description,combo:hero.combo||`Q ${hero.skills[0].name} → E ${hero.skills[2].name} → R ${hero.skills[3].name}`,difficulty:hero.difficulty||2};}
 showSkill(key){const skill=CHAMPIONS.find(h=>h.id===this.heroId).skills.find(s=>s.key===key);$('hero-skill-description').textContent=`${skill.name} · ${skill.description}${skill.passive?'':` 消耗 ${skill.cost} / 冷却 ${skill.cooldown} 秒`}`;document.querySelectorAll('[data-preview-skill]').forEach(b=>b.classList.toggle('selected',b.dataset.previewSkill===key));}
 select(id){if(!CHAMPIONS.some(h=>h.id===id))return;this.heroId=id;this.skinId=equippedSkin(this.profile,id,SKINS);this.onHero(id);document.documentElement.style.setProperty('--hero-splash',`url('${this.base}assets/${id}-splash.jpg')`);this.renderWallet();this.renderRoster();this.renderDetail();this.preview.setHero(id,this.skinId);}
 renderWallet(){const p=this.profile;$('profile-essence').textContent=p.essence.toLocaleString();$('collection-count').textContent=`已拥有 ${CHAMPIONS.filter(h=>ownsHero(p,h.id)).length} / ${CHAMPIONS.length}`;const daily=$('daily-supply');daily.disabled=p.daily===today();daily.textContent=daily.disabled?'今日补给已领取':'每日补给 +1,200';}
 renderRoster(){const query=$('hero-search').value.trim().toLowerCase();document.querySelectorAll('#hero-filters button').forEach(b=>{b.classList.toggle('active',b.dataset.role===this.role);b.setAttribute('aria-pressed',b.dataset.role===this.role);});
  const heroes=CHAMPIONS.filter(h=>(this.role==='all'||this.role==='owned'&&ownsHero(this.profile,h.id)||h.role.includes(this.role))&&(!query||`${h.name} ${h.id} ${h.title} ${h.role} ${h.skills.map(s=>s.name+' '+s.description).join(' ')}`.toLowerCase().includes(query)));
  $('hero-grid').innerHTML=heroes.length?heroes.map(h=>{const owned=ownsHero(this.profile,h.id),s=this.style(h);return `<button class="hero-card ${h.id===this.heroId?'selected':''} ${owned?'owned':'locked'}" data-hero="${h.id}" aria-pressed="${h.id===this.heroId}" aria-label="${h.name}，${owned?'已拥有':heroPrice(h.id)+' 蓝色精粹解锁'}" style="--hero-color:${h.color}"><img src="${this.base}assets/${h.id}-splash.jpg" alt="${h.name}" loading="lazy" draggable="false"><span class="hero-role">${h.role.split(' · ')[0]}</span><div class="hero-card-info"><span class="hero-card-title">${h.title}</span><h3>${h.name}</h3><span class="hero-difficulty">${'◆'.repeat(s.difficulty)}${'◇'.repeat(3-s.difficulty)}</span></div><span class="hero-unlock-tag">${owned?'已拥有':'◆ '+heroPrice(h.id).toLocaleString()}</span></button>`;}).join(''):'<p class="roster-empty">没有匹配的英雄，试试其他名称或分类。</p>';
 }
 renderDetail(){const h=CHAMPIONS.find(c=>c.id===this.heroId),s=this.style(h),owned=ownsHero(this.profile,h.id);$('hero-title').textContent=`${h.name} · ${s.heading}`;$('hero-description').textContent=s.description;$('hero-combo').textContent=s.combo;$('hero-passive').textContent=h.passive?`${h.passive.name} · ${h.passive.description}`:'';$('hero-skills-preview').innerHTML=h.skills.map(skill=>`<button class="preview-skill" data-preview-skill="${skill.key}" title="${skill.description}"><img src="${this.base}assets/${h.id}-${skill.key}.png" alt=""><b>${skill.key}</b><small>${skill.name}</small></button>`).join('');$('hero-ownership').textContent=owned?'已拥有':`${heroPrice(h.id).toLocaleString()} 精粹`;$('hero-ownership').classList.toggle('is-locked',!owned);this.showSkill('Q');const unlock=$('unlock-hero');unlock.classList.toggle('hidden',owned);unlock.disabled=this.profile.essence<heroPrice(h.id);unlock.textContent=unlock.disabled?`精粹不足，还差 ${(heroPrice(h.id)-this.profile.essence).toLocaleString()}`:`解锁 ${h.name} · ◆ ${heroPrice(h.id).toLocaleString()}`;this.renderSkins();this.updateStart();}
 renderSkins(){const skins=SKINS.filter(s=>s.championId===this.heroId),equipped=equippedSkin(this.profile,this.heroId,SKINS);$('skin-options').innerHTML=[{id:'default',name:'经典外观',color:'#8ba6a7',accent:'#d1bd7e',description:'英雄的经典造型。'},...skins].map(s=>`<button class="skin-option ${this.skinId===s.id?'selected':''}" data-skin="${s.id}" aria-pressed="${this.skinId===s.id}" style="--skin-color:${cssColor(s.color)};--skin-accent:${cssColor(s.accent)}"><span class="skin-art ${s.theme||'classic'}"><i></i><b>◆</b><i></i></span><strong>${s.name}</strong><small>${s.id===equipped?'已装备':s.id==='default'||this.profile.skins.includes(s.id)?'已拥有':'◆ '+s.price.toLocaleString()}</small></button>`).join('');const skin=getSkin(this.skinId),owned=ownsHero(this.profile,this.heroId),action=$('skin-action');$('skin-description').textContent=skin?.description||'经典英雄外观，无需额外解锁。';$('preview-theme').textContent=skin?.name||'经典外观';action.classList.toggle('hidden',equipped===this.skinId);action.disabled=!owned||!!skin&&!this.profile.skins.includes(skin.id)&&this.profile.essence<skin.price;action.textContent=!owned?'先解锁英雄后可购买皮肤':this.skinId==='default'||this.profile.skins.includes(this.skinId)?'装备此皮肤':this.profile.essence<skin.price?`精粹不足，还差 ${skin.price-this.profile.essence}`:`解锁并装备 · ◆ ${skin.price.toLocaleString()}`;}
 updateStart(){const trial=$('practice-toggle').checked,owned=ownsHero(this.profile,this.heroId);$('start-game').disabled=!owned&&!trial;$('start-game').querySelector('span').textContent=trial?'进入练习 · 免费试用':owned?'进入峡谷':'先解锁英雄';}
 render(dt){this.preview.render(dt);}
}
