export const ITEMS = [
  {id:'doran-blade',name:'多兰之刃',cost:450,description:'+10 攻击力 · +80 生命 · 3% 生命偷取',icon:'blade',riotId:1055,category:'starter',sellRate:.4,stats:{attack:10,hp:80,lifesteal:.03}},
  {id:'doran-ring',name:'多兰之戒',cost:400,description:'+18 法术强度 · +70 生命 · 法力回复',icon:'ring',riotId:1056,category:'starter',sellRate:.4,stats:{ap:18,hp:70,manaRegen:2}},
  {id:'boots',name:'速度之靴',cost:300,description:'+2 移动速度 · 只能装备一双鞋',icon:'boots',riotId:1001,category:'boots',uniqueGroup:'boots',stats:{speed:2}},
  {id:'berserkers',name:'狂战士胫甲',cost:1100,description:'+4 移动速度 · +35% 攻击速度',icon:'boots',riotId:3006,category:'boots',unique:true,uniqueGroup:'boots',recipe:['boots','dagger','dagger'],stats:{speed:4,attackSpeed:.35}},
  {id:'infinity',name:'无尽之刃',cost:3600,description:'+70 攻击力 · +25% 暴击率 · 强化暴击',icon:'blade',riotId:3031,category:'legendary',unique:true,recipe:['bf-sword','pickaxe','cloak-of-agility'],stats:{attack:70,crit:.25,critPower:.35}},
  {id:'rabadon',name:'灭世者的死亡之帽',cost:3600,description:'+100 法术强度 · 总法术强度提升 30%',icon:'hat',riotId:3089,category:'legendary',unique:true,recipe:['needlessly-large-rod','needlessly-large-rod'],stats:{ap:100,apMultiplier:.3}},
  {id:'ludens',name:'卢登的回声',cost:2850,description:'+75 法术强度 · +300 法力 · +15 技能急速',icon:'orb',riotId:6655,category:'legendary',unique:true,recipe:['lost-chapter','blasting-wand'],stats:{ap:75,mana:300,haste:15}},
  {id:'blade-ruined',name:'破败王者之刃',cost:3200,description:'+40 攻击力 · +25% 攻速 · +10% 吸血；普攻附加目标当前生命 7% 物理伤害',icon:'blade',riotId:3153,category:'legendary',unique:true,passive:'ruined',recipe:['vampiric-scepter','recurve-bow','pickaxe'],stats:{attack:40,attackSpeed:.25,lifesteal:.1}},
  {id:'sunfire',name:'日炎圣盾',cost:2700,description:'+450 生命 · +45 护甲；每秒灼烧附近敌人 20 + 2×等级 魔法伤害',icon:'shield',riotId:3068,category:'legendary',unique:true,passive:'immolate',recipe:['bamis-cinder','chain-vest','ruby-crystal'],stats:{hp:450,armor:45}},
  {id:'zhonya',name:'中娅沙漏',cost:3250,description:'+80 法术强度 · +40 护甲，主动：凝滞 2.5 秒',icon:'hourglass',riotId:3157,category:'legendary',unique:true,recipe:['seeker-armguard','needlessly-large-rod','cloth-armor'],stats:{ap:80,armor:40},active:'stasis'},
  {id:'potion',name:'生命药水',cost:50,description:'主动使用：6 秒内恢复 150 点生命 · 最多叠加 5 瓶',icon:'potion',riotId:2003,category:'consumable',stackLimit:5,sellRate:.4,stats:{},active:'heal'},
  {id:'control-ward',name:'控制守卫',cost:75,description:'主动使用：在附近放置持续 150 秒的真视守卫 · 最多叠加 2 个',icon:'ward',riotId:2055,category:'consumable',stackLimit:2,sellRate:.4,stats:{},active:'ward'},
  {id:'long-sword',name:'长剑',cost:350,description:'+10 攻击力',icon:'blade',riotId:1036,category:'component',stats:{attack:10}},
  {id:'amplifying-tome',name:'增幅典籍',cost:400,description:'+20 法术强度',icon:'book',riotId:1052,category:'component',stats:{ap:20}},
  {id:'ruby-crystal',name:'红水晶',cost:400,description:'+150 生命',icon:'gem',riotId:1028,category:'component',stats:{hp:150}},
  {id:'sapphire-crystal',name:'蓝水晶',cost:350,description:'+250 法力',icon:'gem',riotId:1027,category:'component',stats:{mana:250}},
  {id:'dagger',name:'短剑',cost:250,description:'+12% 攻击速度',icon:'blade',riotId:1042,category:'component',stats:{attackSpeed:.12}},
  {id:'cloth-armor',name:'布甲',cost:300,description:'+15 护甲',icon:'shield',riotId:1029,category:'component',stats:{armor:15}},
  {id:'chain-vest',name:'锁子甲',cost:800,description:'+40 护甲',icon:'shield',riotId:1031,category:'epic',recipe:['cloth-armor'],stats:{armor:40}},
  {id:'bf-sword',name:'暴风大剑',cost:1300,description:'+40 攻击力',icon:'blade',riotId:1038,category:'component',stats:{attack:40}},
  {id:'pickaxe',name:'十字镐',cost:875,description:'+25 攻击力',icon:'blade',riotId:1037,category:'component',stats:{attack:25}},
  {id:'blasting-wand',name:'爆裂魔杖',cost:850,description:'+40 法术强度',icon:'wand',riotId:1026,category:'component',stats:{ap:40}},
  {id:'needlessly-large-rod',name:'无用大棒',cost:1200,description:'+60 法术强度',icon:'wand',riotId:1058,category:'component',stats:{ap:60}},
  {id:'cloak-of-agility',name:'灵巧披风',cost:600,description:'+15% 暴击率',icon:'cloak',riotId:1018,category:'component',stats:{crit:.15}},
  {id:'recurve-bow',name:'反曲之弓',cost:700,description:'+25% 攻击速度',icon:'bow',riotId:1043,category:'epic',recipe:['dagger','dagger'],stats:{attackSpeed:.25}},
  {id:'vampiric-scepter',name:'吸血鬼节杖',cost:900,description:'+15 攻击力 · +7% 生命偷取',icon:'blade',riotId:1053,category:'epic',recipe:['long-sword'],stats:{attack:15,lifesteal:.07}},
  {id:'lost-chapter',name:'遗失的章节',cost:1200,description:'+35 法术强度 · +300 法力 · +10 技能急速',icon:'book',riotId:3802,category:'epic',recipe:['amplifying-tome','sapphire-crystal'],stats:{ap:35,mana:300,haste:10}},
  {id:'bamis-cinder',name:'斑比的熔渣',cost:900,description:'+200 生命',icon:'orb',riotId:6660,category:'epic',recipe:['ruby-crystal'],stats:{hp:200}},
  {id:'fiendish-codex',name:'恶魔法典',cost:850,description:'+30 法术强度 · +10 技能急速',icon:'book',riotId:3108,category:'epic',recipe:['amplifying-tome'],stats:{ap:30,haste:10}},
  {id:'seeker-armguard',name:'探索者的护臂',cost:1200,description:'+20 法术强度 · +25 护甲',icon:'shield',riotId:2420,category:'epic',recipe:['amplifying-tome','cloth-armor'],stats:{ap:20,armor:25}},
];

ITEMS.push(
  {id:'null-magic-mantle',name:'抗魔斗篷',cost:450,riotId:1033,category:'component',stats:{magicResist:20},description:'+20 魔法抗性'},
  {id:'negatron-cloak',name:'负极斗篷',cost:850,riotId:1057,category:'epic',recipe:['null-magic-mantle'],stats:{magicResist:40},description:'+40 魔法抗性'},
  {id:'faerie-charm',name:'仙女护符',cost:250,riotId:1004,category:'component',stats:{manaRegen:2},description:'+2 每秒法力回复'},
  {id:'rejuvenation-bead',name:'治疗宝珠',cost:250,riotId:1006,category:'component',stats:{hpRegen:3},description:'+3 每秒生命回复'},
  {id:'tear',name:'女神之泪',cost:400,riotId:3070,category:'component',stats:{mana:240},description:'+240 法力'},
  {id:'kindlegem',name:'燃烧宝石',cost:800,riotId:3067,category:'epic',recipe:['ruby-crystal'],stats:{hp:200,haste:10},description:'+200 生命 · +10 技能急速'},
  {id:'giants-belt',name:'巨人腰带',cost:900,riotId:1011,category:'epic',recipe:['ruby-crystal'],stats:{hp:350},description:'+350 生命'},
  {id:'caulfield',name:'考尔菲德的战锤',cost:1050,riotId:3133,category:'epic',recipe:['long-sword','long-sword'],stats:{attack:25,haste:10},description:'+25 攻击力 · +10 技能急速'},
  {id:'serrated-dirk',name:'锯齿短匕',cost:1000,riotId:3134,category:'epic',recipe:['long-sword','long-sword'],stats:{attack:20,lethality:10},description:'+20 攻击力 · +10 固定护甲穿透'},
  {id:'sheen',name:'耀光',cost:900,riotId:3057,category:'epic',uniqueGroup:'spellblade',passive:'spellblade',recipe:['sapphire-crystal'],stats:{mana:200,haste:10},description:'+200 法力 · +10 技能急速；施法后下一次普攻附加 100% 基础攻击力伤害，冷却 1.5 秒'},
  {id:'aether-wisp',name:'以太精魂',cost:850,riotId:3113,category:'epic',recipe:['amplifying-tome'],stats:{ap:30,speed:.75},description:'+30 法术强度 · +0.75 移动速度'},
  {id:'winged-moonplate',name:'翼月板甲',cost:800,riotId:3066,category:'epic',recipe:['ruby-crystal'],stats:{hp:150,speed:1},description:'+150 生命 · +1 移动速度'},
  {id:'forbidden-idol',name:'禁忌雕像',cost:800,riotId:3114,category:'epic',recipe:['faerie-charm','faerie-charm'],stats:{manaRegen:5,healShieldPower:.08},description:'+5 每秒法力回复 · 主动装备治疗与护盾增强 8%'},
  {id:'oblivion-orb',name:'湮灭宝珠',cost:800,riotId:3916,category:'epic',passive:'grievous-magic',recipe:['amplifying-tome'],stats:{ap:30},description:'+30 法术强度；魔法伤害降低目标治疗 40%，持续 3 秒'},
  {id:'executioners',name:'死刑宣告',cost:800,riotId:3123,category:'epic',passive:'grievous-physical',recipe:['long-sword'],stats:{attack:15},description:'+15 攻击力；物理伤害降低目标治疗 40%，持续 3 秒'},
  {id:'bramble-vest',name:'棘刺背心',cost:800,riotId:3076,category:'epic',passive:'thorns',recipe:['cloth-armor','cloth-armor'],stats:{armor:30},description:'+30 护甲；受到普攻反弹 10 魔法伤害，并降低攻击者治疗 40%'},
  {id:'last-whisper',name:'最后的轻语',cost:1450,riotId:3035,category:'epic',uniqueGroup:'armor-penetration',recipe:['long-sword','pickaxe'],stats:{attack:20,armorPen:.2},description:'+20 攻击力 · +20% 护甲穿透'},
  {id:'hexdrinker',name:'海克斯饮魔刀',cost:1300,riotId:3155,category:'epic',uniqueGroup:'lifeline',passive:'lifeline-magic',recipe:['long-sword','long-sword','null-magic-mantle'],stats:{attack:20,magicResist:25},description:'+20 攻击力 · +25 魔抗；魔法伤害令生命低于 30% 时获得 150 护盾，冷却 90 秒'},
  {id:'tiamat',name:'提亚马特',cost:1200,riotId:3077,category:'epic',uniqueGroup:'hydra',passive:'cleave',recipe:['long-sword','long-sword'],stats:{attack:20},description:'+20 攻击力；普攻对目标周围敌人造成 35% 攻击力物理伤害'},
  {id:'zeal',name:'狂热',cost:1200,riotId:3086,category:'epic',recipe:['dagger','cloak-of-agility'],stats:{attackSpeed:.15,crit:.15,speed:.5},description:'+15% 攻速 · +15% 暴击率 · +0.5 移动速度'},
  {id:'phage',name:'净蚀',cost:1100,riotId:3044,category:'epic',recipe:['long-sword','ruby-crystal'],stats:{attack:15,hp:200},description:'+15 攻击力 · +200 生命'},
  {id:'hextech-alternator',name:'海克斯科技发电机',cost:1100,riotId:3145,category:'epic',recipe:['amplifying-tome','ruby-crystal'],stats:{ap:30,hp:150},description:'+30 法术强度 · +150 生命'},
  {id:'blighting-jewel',name:'枯萎之珠',cost:1200,riotId:4630,category:'epic',uniqueGroup:'magic-penetration',recipe:['amplifying-tome'],stats:{ap:25,magicPenPercent:.15},description:'+25 法术强度 · +15% 魔法穿透'},
  {id:'haunting-guise',name:'幽魂面具',cost:1300,riotId:3147,category:'epic',recipe:['amplifying-tome','ruby-crystal'],stats:{ap:25,hp:200},description:'+25 法术强度 · +200 生命'},
  {id:'catalyst',name:'万世催化石',cost:1300,riotId:3010,category:'epic',recipe:['ruby-crystal','sapphire-crystal'],stats:{hp:250,mana:300},description:'+250 生命 · +300 法力'},
  {id:'wardens-mail',name:'守望者铠甲',cost:1000,riotId:3082,category:'epic',recipe:['cloth-armor','cloth-armor'],stats:{armor:35,attackReduction:.05},description:'+35 护甲 · 受到的普攻伤害降低 5%'},
  {id:'glacial-buckler',name:'冰川护甲',cost:900,riotId:3024,category:'epic',recipe:['cloth-armor','sapphire-crystal'],stats:{armor:20,mana:250,haste:10},description:'+20 护甲 · +250 法力 · +10 技能急速'},
  {id:'spectres-cowl',name:'幽魂斗篷',cost:1250,riotId:3211,category:'epic',recipe:['null-magic-mantle','ruby-crystal'],stats:{hp:200,magicResist:30,hpRegen:5},description:'+200 生命 · +30 魔抗 · +5 每秒生命回复'},
  {id:'aegis',name:'军团圣盾',cost:1200,riotId:3105,category:'epic',recipe:['cloth-armor','null-magic-mantle'],stats:{armor:25,magicResist:25},description:'+25 护甲 · +25 魔抗'},
  {id:'bandleglass',name:'班德尔玻璃镜',cost:1000,riotId:4642,category:'epic',recipe:['amplifying-tome','faerie-charm'],stats:{ap:20,hp:100,manaRegen:2},description:'+20 法术强度 · +100 生命 · +2 每秒法力回复'},
  {id:'mercury-treads',name:'水银之靴',cost:1100,riotId:3111,category:'boots',unique:true,uniqueGroup:'boots',recipe:['boots','null-magic-mantle'],stats:{speed:4,magicResist:25,tenacity:.3},description:'+4 移动速度 · +25 魔抗 · 控制持续时间缩短 30%'},
  {id:'plated-steelcaps',name:'铁板靴',cost:1200,riotId:3047,category:'boots',unique:true,uniqueGroup:'boots',recipe:['boots','cloth-armor'],stats:{speed:4,armor:25,attackReduction:.12},description:'+4 移动速度 · +25 护甲 · 受到的普攻伤害降低 12%'},
  {id:'sorcerer-shoes',name:'法师之靴',cost:1100,riotId:3020,category:'boots',unique:true,uniqueGroup:'boots',recipe:['boots','amplifying-tome'],stats:{speed:4,magicPen:15},description:'+4 移动速度 · +15 固定魔法穿透'},
  {id:'ionian-boots',name:'明朗之靴',cost:900,riotId:3158,category:'boots',unique:true,uniqueGroup:'boots',recipe:['boots'],stats:{speed:4,haste:15},description:'+4 移动速度 · +15 技能急速'},
  {id:'swift-boots',name:'轻灵之靴',cost:1000,riotId:3009,category:'boots',unique:true,uniqueGroup:'boots',recipe:['boots'],stats:{speed:5,slowResist:.25},description:'+5 移动速度 · 减速强度降低 25%'},
  {id:'essence-reaver',name:'夺萃之镰',cost:2900,riotId:3508,category:'legendary',unique:true,uniqueGroup:'spellblade',passive:'spellblade-mana',recipe:['sheen','caulfield','cloak-of-agility'],stats:{attack:55,crit:.25,haste:20},description:'+55 攻击力 · +25% 暴击 · +20 急速；施法后普攻附加基础攻击力伤害并恢复 30 法力'},
  {id:'collector',name:'收集者',cost:3000,riotId:6676,category:'legendary',unique:true,recipe:['serrated-dirk','pickaxe','cloak-of-agility'],stats:{attack:55,crit:.25,lethality:10},description:'+55 攻击力 · +25% 暴击率 · +10 固定护甲穿透'},
  {id:'lord-dominik',name:'多米尼克领主的致意',cost:3200,riotId:3036,category:'legendary',unique:true,uniqueGroup:'armor-penetration',recipe:['last-whisper','cloak-of-agility'],stats:{attack:40,crit:.25,armorPen:.35},description:'+40 攻击力 · +25% 暴击率 · +35% 护甲穿透'},
  {id:'mortal-reminder',name:'凡性的提醒',cost:3000,riotId:3033,category:'legendary',unique:true,uniqueGroup:'armor-penetration',passive:'grievous-physical',recipe:['last-whisper','executioners','cloak-of-agility'],stats:{attack:30,crit:.25,armorPen:.3},description:'+30 攻击力 · +25% 暴击 · +30% 护甲穿透；物理伤害降低治疗 40%'},
  {id:'black-cleaver',name:'黑色切割者',cost:3000,riotId:3071,category:'legendary',unique:true,passive:'cleaver',recipe:['caulfield','kindlegem','ruby-crystal'],stats:{attack:40,hp:400,haste:20},description:'+40 攻击力 · +400 生命 · +20 急速；物理伤害削减护甲 5%，最多叠加 6 层，持续 6 秒'},
  {id:'phantom-dancer',name:'幻影之舞',cost:2600,riotId:3046,category:'legendary',unique:true,recipe:['zeal','dagger','dagger'],stats:{attackSpeed:.4,crit:.25,speed:1.5},description:'+40% 攻速 · +25% 暴击率 · +1.5 移动速度'},
  {id:'rapid-firecannon',name:'疾射火炮',cost:2600,riotId:3094,category:'legendary',unique:true,recipe:['zeal','dagger'],stats:{attackSpeed:.35,crit:.25,attackRange:3},description:'+35% 攻速 · +25% 暴击率 · 远程英雄普攻范围增加 3'},
  {id:'runaans',name:'卢安娜的飓风',cost:2700,riotId:3085,category:'legendary',unique:true,passive:'hurricane',recipe:['recurve-bow','zeal','dagger'],stats:{attackSpeed:.4,crit:.25},description:'+40% 攻速 · +25% 暴击；远程普攻向另外两名附近敌人射出 40% 攻击力分裂箭'},
  {id:'kraken-slayer',name:'海妖杀手',cost:3100,riotId:6672,category:'legendary',unique:true,passive:'kraken',recipe:['bf-sword','recurve-bow'],stats:{attack:45,attackSpeed:.4},description:'+45 攻击力 · +40% 攻速；每第三次命中普攻附加 40 + 30% 攻击力真实伤害'},
  {id:'nashors-tooth',name:'纳什之牙',cost:3000,riotId:3115,category:'legendary',unique:true,passive:'nashor',recipe:['recurve-bow','fiendish-codex','blasting-wand'],stats:{ap:70,attackSpeed:.4,haste:15},description:'+70 法强 · +40% 攻速 · +15 急速；普攻附加 20 + 20% 法强魔法伤害'},
  {id:'lich-bane',name:'巫妖之祸',cost:3000,riotId:3100,category:'legendary',unique:true,uniqueGroup:'spellblade',passive:'spellblade-magic',recipe:['sheen','aether-wisp','blasting-wand'],stats:{ap:70,speed:1,haste:15},description:'+70 法强 · +1 移速 · +15 急速；施法后普攻附加 75% 基础攻击力 + 40% 法强魔法伤害'},
  {id:'trinity-force',name:'三相之力',cost:3333,riotId:3078,category:'legendary',unique:true,uniqueGroup:'spellblade',passive:'spellblade-trinity',recipe:['sheen','phage','recurve-bow'],stats:{attack:35,attackSpeed:.3,hp:300,haste:20},description:'+35 攻击 · +30% 攻速 · +300 生命 · +20 急速；施法后普攻附加 200% 基础攻击力物理伤害'},
  {id:'deaths-dance',name:'死亡之舞',cost:3300,riotId:6333,category:'legendary',unique:true,recipe:['caulfield','chain-vest','pickaxe'],stats:{attack:55,armor:45,haste:15},description:'+55 攻击力 · +45 护甲 · +15 技能急速'},
  {id:'steraks',name:'斯特拉克的挑战护手',cost:3200,riotId:3053,category:'legendary',unique:true,uniqueGroup:'lifeline',passive:'lifeline',recipe:['phage','pickaxe','ruby-crystal'],stats:{attack:45,hp:450},description:'+45 攻击力 · +450 生命；受到伤害令生命低于 30% 时获得 350 护盾，冷却 90 秒'},
  {id:'maw',name:'玛莫提乌斯之噬',cost:3100,riotId:3156,category:'legendary',unique:true,uniqueGroup:'lifeline',passive:'lifeline-magic',recipe:['hexdrinker','pickaxe'],stats:{attack:55,magicResist:40,haste:15},description:'+55 攻击力 · +40 魔抗 · +15 急速；魔法伤害令生命低于 30% 时获得 300 护盾，冷却 90 秒'},
  {id:'wits-end',name:'智慧末刃',cost:2800,riotId:3091,category:'legendary',unique:true,passive:'wits',recipe:['recurve-bow','negatron-cloak','dagger'],stats:{attackSpeed:.4,magicResist:50},description:'+40% 攻速 · +50 魔抗；普攻附加 40 魔法伤害'},
  {id:'ravenous-hydra',name:'贪欲九头蛇',cost:3300,riotId:3074,category:'legendary',unique:true,uniqueGroup:'hydra',passive:'cleave',recipe:['tiamat','vampiric-scepter','caulfield'],stats:{attack:60,lifesteal:.12,haste:20},description:'+60 攻击力 · +12% 吸血 · +20 急速；普攻对目标周围敌人造成 60% 攻击力物理伤害'},
  {id:'titanic-hydra',name:'巨型九头蛇',cost:3300,riotId:3748,category:'legendary',unique:true,uniqueGroup:'hydra',passive:'cleave-health',recipe:['tiamat','giants-belt','ruby-crystal'],stats:{attack:40,hp:500},description:'+40 攻击力 · +500 生命；普攻对目标周围敌人造成 30% 攻击力 + 2% 最大生命物理伤害'},
  {id:'shadowflame',name:'影焰',cost:3200,riotId:4645,category:'legendary',unique:true,recipe:['needlessly-large-rod','hextech-alternator'],stats:{ap:90,magicPen:15},description:'+90 法术强度 · +15 固定魔法穿透'},
  {id:'void-staff',name:'虚空之杖',cost:3000,riotId:3135,category:'legendary',unique:true,uniqueGroup:'magic-penetration',recipe:['blasting-wand','blighting-jewel'],stats:{ap:80,magicPenPercent:.4},description:'+80 法术强度 · +40% 魔法穿透'},
  {id:'morellonomicon',name:'莫雷洛秘典',cost:2800,riotId:3165,category:'legendary',unique:true,passive:'grievous-magic',recipe:['oblivion-orb','fiendish-codex','ruby-crystal'],stats:{ap:75,hp:250,haste:15},description:'+75 法强 · +250 生命 · +15 急速；魔法伤害降低目标治疗 40%，持续 3 秒'},
  {id:'rylai',name:'瑞莱的冰晶节杖',cost:2600,riotId:3116,category:'legendary',unique:true,passive:'rylai',recipe:['blasting-wand','giants-belt','amplifying-tome'],stats:{ap:65,hp:400},description:'+65 法术强度 · +400 生命；魔法技能命中使目标减速 20%，持续 1 秒'},
  {id:'liandry',name:'兰德里的折磨',cost:3000,riotId:6653,category:'legendary',unique:true,passive:'liandry',recipe:['haunting-guise','blasting-wand'],stats:{ap:70,hp:300},description:'+70 法术强度 · +300 生命；魔法技能命中后每秒灼烧目标最大生命 2%，持续 3 秒'},
  {id:'banshee',name:'女妖面纱',cost:3100,riotId:3102,category:'legendary',unique:true,passive:'spellshield',recipe:['needlessly-large-rod','negatron-cloak','amplifying-tome'],stats:{ap:80,magicResist:50},description:'+80 法术强度 · +50 魔抗；每 30 秒格挡一次魔法技能伤害'},
  {id:'cosmic-drive',name:'星界驱驰',cost:3000,riotId:4629,category:'legendary',unique:true,recipe:['fiendish-codex','aether-wisp','ruby-crystal'],stats:{ap:80,hp:300,haste:25,speed:1},description:'+80 法强 · +300 生命 · +25 急速 · +1 移速'},
  {id:'horizon-focus',name:'视界专注',cost:2700,riotId:4628,category:'legendary',unique:true,recipe:['hextech-alternator','fiendish-codex','amplifying-tome'],stats:{ap:75,hp:150,haste:20},description:'+75 法术强度 · +150 生命 · +20 技能急速'},
  {id:'seraph',name:'炽天使之拥',cost:3000,riotId:3040,category:'legendary',unique:true,uniqueGroup:'lifeline',passive:'lifeline-mana',recipe:['lost-chapter','tear','needlessly-large-rod'],stats:{ap:70,mana:600,haste:20},description:'+70 法强 · +600 法力 · +20 急速；低于 30% 生命时获得 200 + 20% 最大法力护盾，冷却 90 秒'},
  {id:'rod-of-ages',name:'时光之杖',cost:2800,riotId:6657,category:'legendary',unique:true,recipe:['catalyst','blasting-wand'],stats:{ap:60,hp:400,mana:400,hpRegen:3,manaRegen:2},description:'+60 法强 · +400 生命 · +400 法力 · 每秒回复 3 生命和 2 法力'},
  {id:'thornmail',name:'荆棘之甲',cost:2700,riotId:3075,category:'legendary',unique:true,passive:'thorns',recipe:['bramble-vest','giants-belt'],stats:{armor:70,hp:350},description:'+70 护甲 · +350 生命；受到普攻反弹 10 + 10% 护甲魔法伤害，并降低攻击者治疗 40%'},
  {id:'randuins',name:'兰顿之兆',cost:2700,riotId:3143,category:'legendary',unique:true,active:'randuin',recipe:['wardens-mail','giants-belt'],stats:{armor:60,hp:400,attackReduction:.08},description:'+60 护甲 · +400 生命 · 普攻减伤 8%；主动减速附近敌人 55% 持续 2 秒，冷却 60 秒'},
  {id:'frozen-heart',name:'冰霜之心',cost:2500,riotId:3110,category:'legendary',unique:true,recipe:['wardens-mail','glacial-buckler'],stats:{armor:75,mana:400,haste:20,attackReduction:.08},description:'+75 护甲 · +400 法力 · +20 急速 · 受到的普攻伤害降低 8%'},
  {id:'spirit-visage',name:'振奋盔甲',cost:2900,riotId:3065,category:'legendary',unique:true,recipe:['spectres-cowl','kindlegem','ruby-crystal'],stats:{hp:400,magicResist:50,haste:10,hpRegen:5},description:'+400 生命 · +50 魔抗 · +10 急速 · +5 每秒生命回复'},
  {id:'force-of-nature',name:'自然之力',cost:2800,riotId:4401,category:'legendary',unique:true,recipe:['negatron-cloak','winged-moonplate','ruby-crystal'],stats:{magicResist:60,hp:400,speed:1.5},description:'+60 魔法抗性 · +400 生命 · +1.5 移动速度'},
  {id:'warmogs',name:'狂徒铠甲',cost:3000,riotId:3083,category:'legendary',unique:true,passive:'warmog',recipe:['giants-belt','kindlegem','rejuvenation-bead'],stats:{hp:800,hpRegen:6},description:'+800 生命 · +6 每秒生命回复；6 秒未受伤时每秒额外恢复最大生命 5%'},
  {id:'deadmans',name:'亡者的板甲',cost:2900,riotId:3742,category:'legendary',unique:true,recipe:['chain-vest','winged-moonplate','ruby-crystal'],stats:{armor:45,hp:400,speed:1.5},description:'+45 护甲 · +400 生命 · +1.5 移动速度'},
  {id:'jaksho',name:'千变者贾修',cost:3200,riotId:6665,category:'legendary',unique:true,recipe:['chain-vest','negatron-cloak','ruby-crystal'],stats:{hp:350,armor:45,magicResist:45},description:'+350 生命 · +45 护甲 · +45 魔法抗性'},
  {id:'abyssal-mask',name:'深渊面具',cost:2600,riotId:3001,category:'legendary',unique:true,recipe:['negatron-cloak','kindlegem'],stats:{hp:300,magicResist:50,haste:15,magicPen:10},description:'+300 生命 · +50 魔抗 · +15 急速 · +10 固定魔法穿透'},
  {id:'locket',name:'钢铁烈阳之匣',cost:2200,riotId:3190,category:'legendary',unique:true,active:'locket',recipe:['aegis','kindlegem'],stats:{hp:250,armor:30,magicResist:30,haste:10},description:'+250 生命 · +30 护甲和魔抗 · +10 急速；主动给附近友军 200 + 10×等级 护盾，冷却 90 秒'},
  {id:'redemption',name:'救赎',cost:2300,riotId:3107,category:'legendary',unique:true,active:'redemption',recipe:['forbidden-idol','kindlegem'],stats:{hp:300,manaRegen:5,haste:15,healShieldPower:.1},description:'+300 生命 · +5 回蓝 · +15 急速 · 治疗护盾增强 10%；主动治疗落点附近友军 250 + 15×等级，冷却 90 秒'},
  {id:'shurelya',name:'舒瑞亚的战歌',cost:2200,riotId:2065,category:'legendary',unique:true,active:'shurelya',recipe:['bandleglass','aether-wisp'],stats:{ap:40,hp:200,haste:15,manaRegen:3},description:'+40 法强 · +200 生命 · +15 急速 · +3 回蓝；主动让附近友军加速 4 秒，冷却 75 秒'},
  {id:'ardent-censer',name:'炽热香炉',cost:2300,riotId:3504,category:'legendary',unique:true,recipe:['forbidden-idol','aether-wisp','amplifying-tome'],stats:{ap:60,manaRegen:5,healShieldPower:.1},description:'+60 法强 · +5 每秒回蓝 · 主动装备治疗与护盾增强 10%'},
  {id:'staff-flowing-water',name:'流水法杖',cost:2300,riotId:6616,category:'legendary',unique:true,recipe:['forbidden-idol','fiendish-codex','amplifying-tome'],stats:{ap:65,haste:15,manaRegen:5,healShieldPower:.1},description:'+65 法强 · +15 急速 · +5 每秒回蓝 · 主动装备治疗与护盾增强 10%'},
  {id:'moonstone',name:'月石再生器',cost:2400,riotId:6617,category:'legendary',unique:true,recipe:['bandleglass','kindlegem'],stats:{ap:40,hp:250,manaRegen:5,haste:15,healShieldPower:.2},description:'+40 法强 · +250 生命 · +5 回蓝 · +15 急速 · 主动装备治疗与护盾增强 20%'},
  {id:'knights-vow',name:'骑士之誓',cost:2300,riotId:3109,category:'legendary',unique:true,recipe:['kindlegem','chain-vest'],stats:{hp:350,armor:40,haste:10,hpRegen:4},description:'+350 生命 · +40 护甲 · +10 急速 · +4 每秒生命回复'},
  {id:'mikaels',name:'米凯尔的祝福',cost:2300,riotId:3222,category:'legendary',unique:true,active:'mikael',recipe:['forbidden-idol','negatron-cloak'],stats:{hp:250,magicResist:40,manaRegen:5,healShieldPower:.1},description:'+250 生命 · +40 魔抗 · +5 回蓝 · 治疗护盾增强 10%；主动净化鼠标附近友军并恢复 200 生命，冷却 90 秒'},
  {id:'quicksilver-sash',name:'水银饰带',cost:1300,riotId:3140,category:'epic',active:'cleanse',recipe:['null-magic-mantle'],stats:{magicResist:30},description:'+30 魔抗；主动解除自身控制与减速，冷却 90 秒'},
  {id:'mercurial-scimitar',name:'水银弯刀',cost:3000,riotId:3139,category:'legendary',unique:true,active:'cleanse',recipe:['quicksilver-sash','bf-sword'],stats:{attack:40,magicResist:40,lifesteal:.1},description:'+40 攻击力 · +40 魔抗 · +10% 吸血；主动解除自身控制与减速，冷却 90 秒'},
  {id:'rocketbelt',name:'海克斯科技火箭腰带',cost:2600,riotId:3152,category:'legendary',unique:true,active:'rocketbelt',recipe:['hextech-alternator','kindlegem'],stats:{ap:70,hp:250,haste:15},description:'+70 法强 · +250 生命 · +15 急速；主动向鼠标突进并伤害附近敌人，冷却 60 秒'},
  {id:'galeforce',name:'狂风之力',cost:3400,riotId:6671,category:'legendary',unique:true,active:'galeforce',recipe:['bf-sword','recurve-bow','cloak-of-agility'],stats:{attack:55,attackSpeed:.2,crit:.25},description:'+55 攻击力 · +20% 攻速 · +25% 暴击；主动突进并射击最近敌人，冷却 90 秒'},
);

for (const item of ITEMS) {
  if (item.category === 'component' || item.category === 'epic') item.component = true;
  item.icon ||= item.stats.ap ? 'orb' : item.stats.armor || item.stats.magicResist ? 'shield' : 'blade';
  item.tags = [...new Set([...(item.tags || []), ...(item.stats.attack || item.stats.attackSpeed || item.stats.crit ? ['ad'] : []), ...(item.stats.ap ? ['ap'] : []), ...(item.stats.armor || item.stats.magicResist || item.stats.hp >= 300 ? ['tank'] : []), ...(item.stats.healShieldPower || ['locket','shurelya','knights-vow'].includes(item.id) ? ['support'] : []), ...(item.stats.magicResist ? ['mr'] : []), ...(item.stats.armorPen || item.stats.lethality ? ['penetration'] : [])])];
}
