export const ITEMS = [
  {id:'doran-blade',name:'多兰之刃',cost:450,description:'+10 攻击力 · +80 生命 · 3% 生命偷取',icon:'blade',riotId:1055,category:'starter',sellRate:.4,stats:{attack:10,hp:80,lifesteal:.03}},
  {id:'doran-ring',name:'多兰之戒',cost:400,description:'+18 法术强度 · +70 生命 · 法力回复',icon:'ring',riotId:1056,category:'starter',sellRate:.4,stats:{ap:18,hp:70,manaRegen:2}},
  {id:'boots',name:'速度之靴',cost:300,description:'+2 移动速度 · 只能装备一双鞋',icon:'boots',riotId:1001,category:'boots',uniqueGroup:'boots',stats:{speed:2}},
  {id:'berserkers',name:'狂战士胫甲',cost:1100,description:'+4 移动速度 · +35% 攻击速度',icon:'boots',riotId:3006,category:'boots',unique:true,uniqueGroup:'boots',recipe:['boots','dagger','dagger'],stats:{speed:4,attackSpeed:.35}},
  {id:'infinity',name:'无尽之刃',cost:3600,description:'+70 攻击力 · +25% 暴击率 · 强化暴击',icon:'blade',riotId:3031,category:'legendary',unique:true,recipe:['bf-sword','pickaxe','cloak-of-agility'],stats:{attack:70,crit:.25,critPower:.35}},
  {id:'rabadon',name:'灭世者的死亡之帽',cost:3600,description:'+100 法术强度 · 总法术强度提升 30%',icon:'hat',riotId:3089,category:'legendary',unique:true,recipe:['needlessly-large-rod','needlessly-large-rod'],stats:{ap:100,apMultiplier:.3}},
  {id:'ludens',name:'卢登的回声',cost:2850,description:'+75 法术强度 · +300 法力 · +15 技能急速',icon:'orb',riotId:6655,category:'legendary',unique:true,recipe:['lost-chapter','blasting-wand'],stats:{ap:75,mana:300,haste:15}},
  {id:'blade-ruined',name:'破败王者之刃',cost:3200,description:'+40 攻击力 · +25% 攻速 · +10% 吸血，攻击附带百分比伤害',icon:'blade',riotId:3153,category:'legendary',unique:true,recipe:['vampiric-scepter','recurve-bow','pickaxe'],stats:{attack:40,attackSpeed:.25,lifesteal:.1}},
  {id:'sunfire',name:'日炎圣盾',cost:2700,description:'+450 生命 · +45 护甲，灼烧身边敌人',icon:'shield',riotId:3068,category:'legendary',unique:true,recipe:['bamis-cinder','chain-vest','ruby-crystal'],stats:{hp:450,armor:45}},
  {id:'zhonya',name:'中娅沙漏',cost:3250,description:'+80 法术强度 · +40 护甲，主动：凝滞 2.5 秒',icon:'hourglass',riotId:3157,category:'legendary',unique:true,recipe:['seeker-armguard','needlessly-large-rod','cloth-armor'],stats:{ap:80,armor:40},active:'stasis'},
  {id:'potion',name:'生命药水',cost:50,description:'主动使用：6 秒内恢复 150 点生命 · 最多叠加 5 瓶',icon:'potion',riotId:2003,category:'consumable',stackLimit:5,sellRate:.4,stats:{},active:'heal'},
  {id:'control-ward',name:'控制守卫',cost:75,description:'主动使用：在附近放置持续 150 秒的真视守卫 · 最多叠加 2 个',icon:'ward',riotId:2055,category:'consumable',stackLimit:2,sellRate:.4,stats:{},active:'ward'},
  {id:'long-sword',name:'长剑',cost:350,description:'+10 攻击力',icon:'blade',riotId:1036,category:'component',stats:{attack:10}},
  {id:'amplifying-tome',name:'增幅典籍',cost:400,description:'+20 法术强度',icon:'book',riotId:1052,category:'component',stats:{ap:20}},
  {id:'ruby-crystal',name:'红水晶',cost:400,description:'+150 生命',icon:'gem',riotId:1028,category:'component',stats:{hp:150}},
  {id:'sapphire-crystal',name:'蓝水晶',cost:350,description:'+250 法力',icon:'gem',riotId:1027,category:'component',stats:{mana:250}},
  {id:'dagger',name:'短剑',cost:250,description:'+12% 攻击速度',icon:'blade',riotId:1042,category:'component',stats:{attackSpeed:.12}},
  {id:'cloth-armor',name:'布甲',cost:300,description:'+15 护甲',icon:'shield',riotId:1029,category:'component',stats:{armor:15}},
  {id:'chain-vest',name:'锁子甲',cost:800,description:'+40 护甲',icon:'shield',riotId:1031,category:'epic',recipe:['cloth-armor'],stats:{armor:40}},
  {id:'bf-sword',name:'暴风大剑',cost:1300,description:'+40 攻击力',icon:'blade',riotId:1038,category:'component',stats:{attack:40}},
  {id:'pickaxe',name:'十字镐',cost:875,description:'+25 攻击力',icon:'blade',riotId:1037,category:'component',stats:{attack:25}},
  {id:'blasting-wand',name:'爆裂魔杖',cost:850,description:'+40 法术强度',icon:'wand',riotId:1026,category:'component',stats:{ap:40}},
  {id:'needlessly-large-rod',name:'无用大棒',cost:1200,description:'+60 法术强度',icon:'wand',riotId:1058,category:'component',stats:{ap:60}},
  {id:'cloak-of-agility',name:'灵巧披风',cost:600,description:'+15% 暴击率',icon:'cloak',riotId:1018,category:'component',stats:{crit:.15}},
  {id:'recurve-bow',name:'反曲之弓',cost:700,description:'+25% 攻击速度',icon:'bow',riotId:1043,category:'epic',recipe:['dagger','dagger'],stats:{attackSpeed:.25}},
  {id:'vampiric-scepter',name:'吸血鬼节杖',cost:900,description:'+15 攻击力 · +7% 生命偷取',icon:'blade',riotId:1053,category:'epic',recipe:['long-sword'],stats:{attack:15,lifesteal:.07}},
  {id:'lost-chapter',name:'遗失的章节',cost:1200,description:'+35 法术强度 · +300 法力 · +10 技能急速',icon:'book',riotId:3802,category:'epic',recipe:['amplifying-tome','sapphire-crystal'],stats:{ap:35,mana:300,haste:10}},
  {id:'bamis-cinder',name:'斑比的熔渣',cost:900,description:'+200 生命',icon:'orb',riotId:6660,category:'epic',recipe:['ruby-crystal'],stats:{hp:200}},
  {id:'fiendish-codex',name:'恶魔法典',cost:850,description:'+30 法术强度 · +10 技能急速',icon:'book',riotId:3108,category:'epic',recipe:['amplifying-tome'],stats:{ap:30,haste:10}},
  {id:'seeker-armguard',name:'探索者的护臂',cost:1200,description:'+20 法术强度 · +25 护甲',icon:'shield',riotId:2420,category:'epic',recipe:['amplifying-tome','cloth-armor'],stats:{ap:20,armor:25}},
];

for (const item of ITEMS) if (item.category === 'component' || item.category === 'epic') item.component = true;
